#!/bin/bash

venvdir=".venv"

python3 -m pip install --upgrade pip

echo "[mkvenv] deactivating current venv..."
deactivate 2> /dev/null

echo "[mkvenv] releting existing venv..."
rm -rf $venvdir

echo "[mkvenv] creating new venv..."
python3 -m venv $venvdir

echo "[mkvenv] activating venv..."
source $venvdir/bin/activate

echo "[mkvenv] installing dependencies..."
python -m pip install --upgrade pip
python -m pip install .[dev]
python -m pip install -r requirements.txt
